name: Build AppFlowy Web Docker Hub

on:
  workflow_dispatch:

jobs:
  build-appflowy-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout AppFlowy-Web
        uses: actions/checkout@v4
        with:
          repository: AppFlowy-IO/AppFlowy-Web
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push appflowy_web
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: gwillisyodev/appflowy_web:latest
